#!/usr/bin/env bash
#
# Copyright (C) 2025, David J. Rosenbaum <djr7c4@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of version 3 of the GNU General Public License, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

cleanup() {
    rm "$bootstrap_requirements_file"
}

trap cleanup EXIT

if [[ ! -d ".git" ]]; then
    echo "This script must be run from the top-level of a git repository" >&2
    exit 1
fi

stable_versions() {
    repo="$1"
    git ls-remote "$repo" | awk '{ print $2 }' | sed -n 's:\^{}::; s:^refs/tags/::p' | sort -V | uniq || { echo "Failed to extract the stable versions for $repo" >&2 && return 1; }
}

latest_stable() {
    repo="$1"
    stable_versions "$repo" | tail -n 1 || { echo "Failed to extract the latest stable version for $repo" >&2 && return 1; }
}

stp_repo="https://github.com/djr7C4/subtree-package.git"
bootstrap_requirements_file="$(mktemp)"

stable() {
    name="$1"
    repo="$2"
    [[ "$stp_latest_stable" ]] || stp_latest_stable="$(latest_stable "$stp_repo")"
    bootstrap_requirements_url="https://raw.githubusercontent.com/djr7C4/subtree-package/refs/tags/${stp_latest_stable}/bootstrap-requirements"
    [[ -s "$bootstrap_requirements_file" ]] || curl -s "$bootstrap_requirements_url" > "$bootstrap_requirements_file" || { echo "Failed to download the bootstrap requirements" >&2 && return 1; }
    # Get the version from the "Package-Requires" header in stp.el.
    emacs_package_version="$(cat "$bootstrap_requirements_file" | grep "$name" | cut -d ' ' -f 2)" || { echo "Failed to extract the package version for $name" >&2 && return 1; }
    git_tag="$(stable_versions "$repo" | grep "$emacs_package_version")" || { echo "The git tag for $emacs_package_version of $name was not found" >&2 && return 1; }
    echo "$git_tag"
}

repos=("anaphora https://github.com/rolandwalker/anaphora.git master" "dash https://github.com/magnars/dash.el.git master" "f https://github.com/rejeep/f.el.git master" "memoize https://github.com/djr7C4/emacs-memoize.git master" "s https://github.com/magnars/s.el.git master" "async https://github.com/jwiegley/emacs-async master" "llama https://github.com/tarsius/llama main" "rem https://github.com/djr7C4/rem.git main" "subtree-package https://github.com/djr7C4/subtree-package.git main")

pkg_info_file="stp-pkg-info.eld"

echo "Which version should be installed?"
select version_type in "recommended stable" "latest stable" "unstable"; do break; done

case "$version_type" in
    "recommended stable"|"latest stable")
        update="stable"
        ;;
    "unstable")
        update="unstable"
        ;;
esac

echo "((packages" > "$pkg_info_file"

for item in "${repos[@]}"; do
    name="$(echo "$item" | cut -d ' ' -f 1)"
    repo="$(echo "$item" | cut -d ' ' -f 2)"
    branch="$(echo "$item" | cut -d ' ' -f 3)"

    if [[ "$version_type" = "latest stable" ]]; then
        version="$(latest_stable "$repo")" || exit 1
        branch_cell=""
    elif [[ "$version_type" = "recommended stable" ]]; then
        # subtree-package isn't in the bootstrap requirements file so it needs
        # to be handled specially.
        [[ "$stp_latest_stable" ]] || stp_latest_stable="$(latest_stable "$stp_repo")" || exit 1

        if [[ "$name" = "subtree-package" ]]; then
            version="$stp_latest_stable"
        else
            version="$(stable "$name" "$repo")" || exit 1
        fi

        branch_cell=""
    else
        version="$branch"
        branch_cell=" (branch . \"${branch}\")"
    fi

    if [[ ! "$version" ]]; then
        echo "Unable to detect the version of $name to install" >&2
        read -p "Enter the version: " version
    fi

    echo "Cloning $version of $repo"
    git subtree add --prefix "package-source/${name}" --squash "$repo" "$version"
    echo "(\"${name}\" (method . git) (remote . \"${repo}\") (update . ${update})${branch_cell})" >> "$pkg_info_file" || { echo "Failed to add the git subtree for $repo" >&2 && exit 1; }
done

echo -e "))\n" >> "$pkg_info_file"

echo "Finished installing STP"
