#+title: Welcome to my Lisprvanna
#+author: Klementiev Dmitry
#+email: klementievd08@yandex.ru

This repository contain source code of my Emacs configuration and all
installed packages (see =package-source/=).

* COMMENT Documentation

Recently I start learning rST, Python and Sphinx.

** COMMENT Building Info file for Emacs

Firstly execute following commands in your shell

#+begin_src sh
  $ sphinx-build -b texinfo docs/ docs/_build/texinfo
  $ make -k docs/_build/texinfo
#+end_src

and run =(info "Lisprvanna")=

** COMMENT Other formats

Read *Sphinx* documentation for information about supported
output formats.

* Subtree Package Manager

Special thanks for those beatifull package manager: [[https://github.com/djr7C4/subtree-package][subtree-package]].

All packages in this configurations managed by ~git~ and ~git-subtree~.

** Why all packages in git repository?

Because it's just subtrees. Just clone and run this configuration =)

** Why STP?

Because it's something new and so interesting. I must try it
in my main configuration.

* Modules and Lisp

- lisp/ :: Configuration provided features
- modules/ :: Main source code of my configuration

** Modules

I think my modules is the most easiest way to manage configuration source code.

It's just a lot of source files which placed in subdirectories.

* Running

You have two ways to run this lisprvanna:

1. Clone this repository to =~/.config/emacs= or =~/.emacs.d=.

   More convenient way to run this configuration.

2. Clone this repository anywhere and execute ~./run.sh~ script.

   You can also run Emacs in terminal with ~./run.sh -nw~.

* System Dependencies

1. Git
2. GNU Make
3. Grep, Ripgrep, Find, Locate and etc
4. +TDLib for telega.el+
5. Python
6. /Ollama/
   
* Org Directories

Following org directories structure provided:

- ~/agenda :: Directory with agenda things
- ~/notes :: Directory with Org notes (Org Supertag)

* Supported things

Supported things in my Emacs Workflow.

** Languages

- Emacs Lisp

  My main programming language. I use Emacs a lot in my life and work.

- Python

  My second programming language which I use for scripting.

- Bash language

  I use GNU/Linux. I use Bash for simple automation in my system/workflow.

** Markup

- Org Mode

  I use Emacs a lot --> I use Org Mode a lot.

- reStructuredText

  I love using rST-like syntax in Emacs Lisp comments. I use rST or Sphinx only sometimes.

- Markdown

  Second markup language after Org Mode.

- LaTeX (=pdflatex=, =lualatex=, =xelatex=, =texinfo= and e.t.c.)

  For things like PDF writing, Resume/CV and etc. Also I sometimes read (sometimes also write) TeXinfo format (see gnu texinfo: =.texi=).
