((packages
("anaphora" (method . git) (remote . "https://github.com/rolandwalker/anaphora.git") (update . stable))
("dash" (method . git) (remote . "https://github.com/magnars/dash.el.git") (update . stable))
("f" (method . git) (remote . "https://github.com/rejeep/f.el.git") (update . stable))
("memoize" (method . git) (remote . "https://github.com/djr7C4/emacs-memoize.git") (update . stable))
("s" (method . git) (remote . "https://github.com/magnars/s.el.git") (update . stable))
("async" (method . git) (remote . "https://github.com/jwiegley/emacs-async") (update . stable))
("llama" (method . git) (remote . "https://github.com/tarsius/llama") (update . stable))
("rem" (method . git) (remote . "https://github.com/djr7C4/rem.git") (update . stable))
("subtree-package" (method . git) (remote . "https://github.com/djr7C4/subtree-package.git") (update . stable))
))

