#+title: TODO LIST
#+author: Klementiev Dmitry
#+email: klementievd08@yandex.ru

* DONE Более лучшая версия для макроса =set!=

+Сейчас это просто макрос обёртка над =setq-default=.+

+Думаю стоит либо его убрать полностью и не использовать, либо+
+сделать более лучшую реализацию.+

В итоге я просто удалил данный макрос =).

Думаю в дальнейшем можно будет попробовать реализовать что-то подобное.

* TODO Макрос =after!=

Сейчас это самый основной макрос который определяет всю суть ленивой
загрузки.

Его можно разделить или переделать в =use-package= если я захочу его использовать.

Хотя я против использования =use-package= в своей конфигурации, т.к я хочу
чтобы вся конфигурация была описанна явно и понятна (без всякой магии).

* TODO Другая система модулей.

Пока не знаю что я хочу от этого, но возможно хотелось бы более удобной модульной системы

* TODO Переписать конфигурацию

- [ ] [[*Другая система модулей.][Переделать систему модулей.]]
- [ ] No-prog конфигурация

  Т.е я хочу чтобы переписанная конфигурация не содержала в себе никаких хуёвин для программирования.

  Мне нужна база знаний и просто удобный софт. Программирование будет добавляться позже.

  /Emacs Lisp будет исключением. Так же можно оставить Bash и Python./
