name: Bug Report
description: File a bug report
labels: ["bug"]
assignees: []
body:
  - type: checkboxes
    id: updated-gptel
    attributes:
      label: Please update gptel first -- errors are often fixed by the time they're reported.
      options:
        - label: I have updated gptel to the latest commit and tested that the issue still exists
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a short description of the bug
      placeholder: A clear and concise description of the bug
    validations:
      required: true
  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Is the issue with a particular gptel backend? (Leave blank otherwise)
      options:
        - OpenAI/Azure
        - Ollama
        - Gemini
        - Anthropic
        - Kagi
        - Other (please specify in Additional Context)
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Set '...'
        2. Run '....'
        4. See error '...'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context (e.g., Emacs version, operating system)
      placeholder: |
        Emacs version:
        Operating System:
        Any other information (Curl version, gptel backend etc -- only if relevant):
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Backtrace and log"
  - type: markdown
    attributes:
      value: "#### Backtrace"
  - type: markdown
    attributes:
      value: |
        If an error was signaled, please generate a backtrace as follows:
        1. Run `M-x toggle-debug-on-error`
        2. Reproduce the error
        3. Paste the contents of the backtrace here
  - type: textarea
    id: backtrace
    attributes:
      label: Backtrace
      description: Paste the backtrace here
      render: emacs-lisp
  - type: markdown
    attributes:
      value: "#### Logging and simulation instructions"
  - type: markdown
    attributes:
      value: |
        Depending on the bug, it might be useful to include the data gptel sends and receives from the LLM, or to simulate a request.
                
        **To see gptel's log**
        1. Turn on logging by running `(setq gptel-log-level 'info)`.  Set it to `debug` for more information
        2. Use gptel
        3. Check the `*gptel-log*` buffer

        **For a gptel request dry-run**
        1. Run `(setq gptel-expert-commands t)`
        2. From gptel's menu (`M-x gptel-menu`), use one of the newly visible `dry run` options.
  - type: textarea
    id: log-info
    attributes:
      label: Log Information
      description: (If relevant) paste the relevant log information or dry-run output here
      placeholder: (If relevant) paste the contents of the *gptel-log* buffer or dry-run output here
      render: json
    validations:
      required: false
