blank_issues_enabled: false
contact_links:
  - name: "🙏 Please support @minad"
    url: https://github.com/sponsors/oantolin
    about: See https://github.com/sponsors/minad for sponsoring information.
  - name: "🙏 Please support @oantolin"
    url: https://github.com/sponsors/oantolin
    about: See https://github.com/sponsors/oantolin for sponsoring information.
  - name: "💡 Suggest a feature ➞ Please create a discussion"
    url: https://github.com/minad/marginalia/discussions/categories/ideas
    about: Start a new discussion suggesting an improvement or a feature.
  - name: "🧑‍🤝‍🧑 Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please be kind and support others.
  - name: "🤓 Ask the maintainer for support ➞ Please create a discussion"
    url: https://github.com/minad/marginalia/discussions/categories/q-a
    about: Please keep in mind that our bandwidth is limited.
  - name: "🔍 Search through old issues or discussions"
    url: https://github.com/search?q=repo%3Aminad%2Fmarginalia&type=issues
    about: The same question may have been asked before.
#  - name: "📝 Marginalia wiki"
#    url: https://github.com/minad/marginalia/wiki
#    about: Additional configuration tips are covered there. Feel free to edit!
  - name: "📖 Marginalia manual"
    url: https://github.com/minad/marginalia/blob/main/README.org
    about: The manual covers the basic setup and workflow.
